 <h1>HIRE JAMES WONG FOR TAPFURY!</h1>
    <p>Welcome to our petition! As James Wong's biggest fans, we want our hero to suceed and get the web development internship at TapFury! Not only is he ridiculously handsome, he has demostrated the skills that he needs for the position! I mean, check out his bloated Linkedin profile: <a href="https://www.linkedin.com/profile/view?id=228895274&trk=nav_responsive_tab_profile_pic">Linkedin. </a> In addition to that, he has learned to used the Zend Framework! A very challenging feat that only 1.5% of the population of the world can do, especially with Zend's horrible documentation.</p>
    
    <p>So please, show your support! Sign this petition, and show TapFury that they will make the right choice by hiring our special star, James Wong!
    Just fill out your name, your email, your location, and a short message stating how wonderful James Wong really is. Thank you! 
    </p>

    <?php
    	$this->form->setAction($this->url());
    	echo $this->form;

    	//using a normal constructor
$db = new Zend_Db_Adapter_Pdo_Mysql(array(
    'host'     => 'localhost',
    'username' => 'root',
    'password' => 'root',
    'dbname'   => 'zf_framework_db'
));

	$tables = $db->listTables();
	echo $this->$tables;
    ?>

