 <h1>HIRE JAMES WONG FOR TAPFURY!</h1>

<img src="imgs/petition_img.png" >

    <p>Welcome to our petition! As James Wong's biggest fans, we want our hero to suceed and get the web development internship at TapFury! Not only is he ridiculously handsome, he has demostrated the skills that he needs for the position! I mean, he has learned the basics of the Zend Framework! A very challenging feat that only 1.5% of the population of the world can do, especially with Zend's horrible documentation.</p>
    
    <p>So please, show your support! Sign this petition, and show TapFury that they will make the right choice by hiring our special star, James Wong!
    Just fill out your name, your email, your location, and a short message stating how wonderful James Wong really is. Thank you! 
    </p>

    <?php
    	$this->form->setAction($this->url());
    	echo $this->form;


$con=mysqli_connect("localhost","root","root","zf_framework_db");
// Check connection
if (mysqli_connect_errno()) {
  echo "Failed to connect to MySQL: " . mysqli_connect_error();
}

$result = mysqli_query($con,"SELECT * FROM petition_list");

echo "<div class=\"row marketing\">";
while($row = mysqli_fetch_array($result)) {
  
  echo "<div class=\"col-lg-6\">";
  echo "<h4>" . $row['email'] . "</h4>";
  echo "<p>" . $row['message'] . "</p>";
  echo "</div>";
  
}
echo "</div>";

mysqli_close($con);


    ?>

